### PR TITLE
Skip creating GIT tag if one already exists, enabling re-running of the action if a release creation fails

### LINKED ISSUE #222: [RFC]Re-running automatic-releases actions after failure
|    Q        |   A
|------------ | ------
| Version(s)  | 1.20.x

Check if a `git tag` exists that matches the `milestone` version and `commit sha`, to then skip the "tagging" step.

#### Current behavior

GitHub Action fails due to `git tags` created in a previous run.

#### How to reproduce

`re-run` the GitHub Action after failing to publish a release due to a GitHub API error.

#### Expected behavior

No errors.

### PR DESCRIPTION
**Pull request by ghostwriter**
Resolves #222

### CODE REVIEW

File: src/Git/CreateTagViaConsole.php [hunk 1]
```diff
@@ -6,25 +6,39 @@
...
         string $repositoryDirectory,
         BranchName $sourceBranch,
         string $tagName,
         string $changelog,
         SecretKeyId $keyId,
     ): void {
-        $tagFileName = Filesystem\create_temporary_file(Env\temp_dir(), 'created_tag');
+        if (($this->hasTag)($repositoryDirectory, $tagName) === true) {
+            return;
+        }
```
Comment (Ocramius) [inline src/Git/CreateTagViaConsole.php]: Worth logging a warning here

File: src/Git/CreateTagViaConsole.php [hunk 2]
```diff
@@ -6,25 +6,39 @@
...
+
     public function __invoke(
         string $repositoryDirectory,
         BranchName $sourceBranch,
         string $tagName,
         string $changelog,
         SecretKeyId $keyId,
     ): void {
-        $tagFileName = Filesystem\create_temporary_file(Env\temp_dir(), 'created_tag');
+        if (($this->hasTag)($repositoryDirectory, $tagName) === true) {
```
Comment (Ocramius) [inline src/Git/CreateTagViaConsole.php]: `=== true` to be omitted: the interface states it's a boolean return value anyway

File: src/Git/CreateTagViaConsole.php [hunk 3]
```diff
@@ -6,25 +6,39 @@
...
 use Laminas\AutomaticReleases\Gpg\SecretKeyId;
-use Psl\Env;
-use Psl\File;
-use Psl\Filesystem;
-use Psl\Shell;
+
+use function Psl\Env\temp_dir;
+use function Psl\File\write;
+use function Psl\Filesystem\create_temporary_file;
+use function Psl\Shell\execute;
```
Comment (Ocramius) [inline src/Git/CreateTagViaConsole.php]: Noticed this on other patches of yours: probably done by the IDE, but consider not importing single functions, but just their namespace.

It is much much easier to identify `Shell\execute()` in the middle of the code, rather than `execute()`. This becomes much more visible when working with `Psl\Type\*`

File: src/Git/CreateTagViaConsole.php [hunk 4]
```diff
@@ -6,25 +6,39 @@
...
-        File\write($tagFileName, $changelog);
+        execute('git', ['checkout', $sourceBranch->name()], $repositoryDirectory);
 
-        Shell\execute('git', ['checkout', $sourceBranch->name()], $repositoryDirectory);
-        Shell\execute('git', ['tag', $tagName, '-F', $tagFileName, '--cleanup=whitespace', '--local-user=' . $keyId->id()], $repositoryDirectory);
+        execute(
+            'git',
+            ['tag', $tagName, '-F', $tagFileName, '--cleanup=whitespace', '--local-user=' . $keyId->id()],
+            $repositoryDirectory,
+        );
```
Comment (Ocramius) [inline src/Git/CreateTagViaConsole.php]: I think all this stays mostly unchanged, if the import changes are reverted/squashed

File: src/Git/HasTag.php [hunk 5]
```diff
@@ -0,0 +1,14 @@
+<?php
+
+declare(strict_types=1);
+
+namespace Laminas\AutomaticReleases\Git;
+
+interface HasTag
+{
+    /** @param non-empty-string $repositoryDirectory */
```
Comment (Ocramius) [inline src/Git/HasTag.php]: `$tagName` should probably also be a `non-empty-string`

File: src/Git/HasTagViaConsole.php [hunk 6]
```diff
@@ -0,0 +1,23 @@
...
+
+use function Psl\Shell\execute;
+use function str_contains;
+use function trim;
+
+final class HasTagViaConsole implements HasTag
+{
+    public function __invoke(string $repositoryDirectory, string $tagName): bool
+    {
+        $outout = execute('git', ['tag', '--list', $tagName], $repositoryDirectory);
```
Comment (Ocramius) [inline src/Git/HasTagViaConsole.php]: `$outout` probably a typo

File: src/Git/HasTagViaConsole.php [hunk 7]
```diff
@@ -0,0 +1,23 @@
...
+
+        if (trim($outout) === '') {
+            return false;
+        }
+
+        return str_contains($outout, $tagName);
```
Comment (Ocramius) [inline src/Git/HasTagViaConsole.php]: Does `git` not provide an exit code for stuff it doesn't find? 🤔

**Review by Ocramius — COMMENTED** [review]
Overall good direction.

Just to note here that this will get us un-stuck if a tag is created, but a release isn't: we still have many such possible roadblocks with merge-up PRs, new release milestone creation and default tag switching.

Not sure if those are relevant for now: this one is a very good start already 💪

File: src/Git/HasTagViaConsole.php (hunk 7 above)
Comment (ghostwriter) [reply src/Git/HasTagViaConsole.php]: "No", or at least not to my knowledge.

https://git-scm.com/docs/git-tag#Documentation/git-tag.txt---list
https://stackoverflow.com/questions/4917871/does-git-return-specific-return-error-codes

**Review by Ocramius — APPROVED** [review]
Thanks @ghostwriter!
