### PR TITLE
Fix #198 - make GIT's `safe.directory` `'*'` by default on repository fetch

### LINKED ISSUE #198: `git` broken on latest `1.14.0` image
### Bug Report

`1.14.0` crashes and leaks repository secrets.

|    Q        |   A
|------------ | ------
| Version(s)  | 1.14.0

#### Summary

The `1.14.0` image has now been dropped, as a security precaution.

Two problems arise:

 1. in case of `git` operations failing, we get a crash with un-masked secrets (**really** bad, although not exploitable, luckily)
 2. because `git` added "security" around operating on repositories owned by other users, we have crashing release processes, like https://github.com/scoutapp/scout-apm-php-ext/runs/7518545888?check_suite_focus=true

Related: https://github.com/laminas/laminas-continuous-integration-action/pull/99

### PR DESCRIPTION
**Pull request by Ocramius**
This is an ugly side-effect, and it will modify the environment of users that rely on this package
outside the context of the delivered docker container, but it is a good workaround for the security
and compatibility mess that GIT 2.35.3 introduced.

In fact, this application was never meant to run in multi-user mode, and the container it runs will
not be affected by side effects (mostly git hooks) in freshly checked out code.

Ref: https://stackoverflow.com/a/71904131/347063
Ref: https://git-scm.com/docs/git-config/2.35.2#Documentation/git-config.txt-safedirectory
Ref: https://marc.info/?l=git&m=164989570902912&w=2
Ref: https://github.com/git/git/commit/8959555cee7ec045958f9b6dd62e541affb7e7d9
Ref: https://github.com/git-for-windows/git/issues/3809#issuecomment-1102681740

### CODE REVIEW

File: src/Git/FetchAndSetCurrentUserByReplacingCurrentOriginRemote.php [hunk 1]
```diff
@@ -31,6 +31,7 @@ public function __invoke(
 
         $credentialStore = Filesystem\create_temporary_file();
 
+        Shell\execute('git', ['config', '--global', '--add', 'safe.directory', '*'], $repositoryRootDirectory);
```
Comment (Ocramius) [inline src/Git/FetchAndSetCurrentUserByReplacingCurrentOriginRemote.php:34]: Ugly but necessary :-\

**Review by boesing — APPROVED** [review]
LGTM.
The test looks a bit weird as it supposed to be an integration test since you are validating that the command was executed but I don't want to be too picky here.

**Comment by Ocramius** [comment]
:ship: 

Trying out a release ASAP.
