### PR TITLE
Private repository release support

### LINKED ISSUE #139: Release for a private repository
### Bug Report

I've been using automatic-releses for my open-source projects for some time, but yesterday I tried on a private repository and I'm getting a 422 error during fetchMilestoneIssues.

|    Q        |   A
|------------ | ------
| Version(s)  | <=1.12.0

#### Summary

If I try to release to a private repository, the ```fetchMilestoneIssues``` within the ```jwage/changelog-generator``` fails with a 422 error because it does not have the github credentials.

I tested on 1.11.1 and 1.12.0. I'm opening a PR for a fix in a few minutes.

#### Current behavior

```
In IssueClient.php line 56:
  [RuntimeException]
  API call to GitHub failed with status code 422 and message "Validation Failed"

Exception trace:
  at /app/vendor/jwage/changelog-generator/src/ChangelogGenerator/IssueClient.php:56
 ChangelogGenerator\IssueClient->execute() at /app/vendor/jwage/changelog-generator/src/ChangelogGenerator/IssueFetcher.php:32
 ChangelogGenerator\IssueFetcher->fetchMilestoneIssues() at /app/vendor/jwage/changelog-generator/src/ChangelogGenerator/IssueRepository.php:24
 ChangelogGenerator\IssueRepository->getMilestoneIssues() at /app/vendor/jwage/changelog-generator/src/ChangelogGenerator/ChangelogGenerator.php:36
 ChangelogGenerator\ChangelogGenerator->generate() at /app/src/Github/JwageGenerateChangelog.php:54
 Laminas\AutomaticReleases\Github\JwageGenerateChangelog->__invoke() at /app/src/Github/CreateReleaseTextThroughChangelog.php:50
 Laminas\AutomaticReleases\Github\CreateReleaseTextThroughChangelog->__invoke() at /app/src/Github/MergeMultipleReleaseNotes.php:39
 Laminas\AutomaticReleases\Github\MergeMultipleReleaseNotes::Laminas\AutomaticReleases\Github\{closure}() at /app/vendor/azjezz/psl/src/Psl/Vec/map.php:38
 Psl\Vec\{closure}() at n/a:n/a
 array_map() at /app/vendor/azjezz/psl/src/Psl/Vec/map.php:39
 Psl\Vec\map() at /app/src/Github/MergeMultipleReleaseNotes.php:40
 Laminas\AutomaticReleases\Github\MergeMultipleReleaseNotes->__invoke() at /app/src/Application/Command/ReleaseCommand.php:86
 Laminas\AutomaticReleases\Application\Command\ReleaseCommand->execute() at /app/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /app/vendor/symfony/console/Application.php:971
 Symfony\Component\Console\Application->doRunCommand() at /app/vendor/symfony/console/Application.php:290
 Symfony\Component\Console\Application->doRun() at /app/vendor/symfony/console/Application.php:166
 Symfony\Component\Console\Application->run() at /app/bin/console.php:169
 Laminas\AutomaticReleases\WebApplication\{closure}() at /app/bin/console.php:170

laminas:automatic-releases:release
```

#### How to reproduce

Install the action on a private repository.

#### Expected behavior

Release done successfully.

### PR DESCRIPTION
**Pull request by Lansoweb**
Fixing [#139](https://github.com/laminas/automatic-releases/issues/139) to allow usage on private repositories.

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

Fixes #139

### CODE REVIEW

File: src/Github/JwageGenerateChangelog.php [hunk 1]
```diff
@@ -20,23 +21,26 @@
...
+        GitHubCredentials $gitHubCredentials
     ): self {
         $issueClient     = new IssueClient($messageFactory, $client);
         $issueFactory    = new IssueFactory();
         $issueFetcher    = new IssueFetcher($issueClient);
         $issueRepository = new IssueRepository($issueFetcher, $issueFactory);
         $issueGrouper    = new IssueGrouper();
 
-        return new self(new ChangelogGenerator($issueRepository, $issueGrouper));
+        return new self(new ChangelogGenerator($issueRepository, $issueGrouper), $gitHubCredentials);
```
Comment (Ocramius) [inline src/Github/JwageGenerateChangelog.php:43]: I think this code path is not tested, hence why the build fails: can it be covered with a new test that just verifies that a `JwageGenerateChangelog` is produced?

**Review by Ocramius — CHANGES_REQUESTED** [review]

File: src/Github/JwageGenerateChangelog.php (hunk 1 above)
Comment (Lansoweb) [reply src/Github/JwageGenerateChangelog.php:43]: Absolutely. Not at home right now but I’ll do it later, thanks!

File: test/unit/Github/JwageGenerateChangelogTest.php [hunk 2]
```diff
@@ -32,7 +41,22 @@ public function testGenerateChangelog(): void
...
+        $httpClient   = $this->createMock(HttpClient::class);
+        $githubToken  = $this->createMock(GitHubCredentials::class);
+
+        $changeLogGenerator = JwageGenerateChangelog::create(
+            $makeRequests,
+            $httpClient,
+            $githubToken
+        );
+
+        $this->assertInstanceOf(JwageGenerateChangelog::class, $changeLogGenerator);
```
Comment (Ocramius) [inline test/unit/Github/JwageGenerateChangelogTest.php:58]: This isn't really testing anything (the type declarations already do this for us): is there a way for us to somehow verify that the credentials were set?

Comment (Lansoweb) [reply test/unit/Github/JwageGenerateChangelogTest.php:58]: Yes, during the __invoke call, I'll add the test.

Comment (Lansoweb) [reply test/unit/Github/JwageGenerateChangelogTest.php:58]: @Ocramius The token is used only [here](https://github.com/Lansoweb/automatic-releases/blob/private-repository/src/Github/JwageGenerateChangelog.php#L54) to create a ```ChangelogConfig``` to be used by the ```JwageGenerateChangelog```.

Comment (Ocramius) [reply test/unit/Github/JwageGenerateChangelogTest.php:58]: Yeh, it's just that the test as-is will surely be marked as invalid in future iterations of the psalm PHPUnit plugin, because there is a 100% type match here, so the assertion will be detected as redundant.

In practice I'm OK with this patch as-is, and to improve the test in a later iteration.

**Review by Ocramius — APPROVED** [review]
LGTM, even considering test issues discussed.

Will tag a release immediately :-)

**Comment by Lansoweb** [comment]
Thanks a lot! It's working now :)

image
